### PR TITLE
nfp: Amiibo scanning support

### LINKED ISSUE #1472: nfp:user IUser: 3 (StartDetection) is not implemented
## Bug Report

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000c43b0 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> >, 8ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >::ProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 4ul, void>, unsigned int)
   sdk:0x00133728 Sub000000000ad9a728
   sdk:0x0012f534 nn::nfp::StartDetection(nn::nfp::DeviceHandle const&)
   main:0x0095f6c0 al::NfpControllerThread::executeCommandStartDetection()
   main:0x0095f120 al::NfpControllerThread::executeCommand(sead::Thread*, long)
   main:0x0075b040 sead::Thread::run_()
   main:0x0075a908 sead::Thread::ninThreadFunc_(void*)
   sdk:0x0008a8a8 Sub000000000acf18a8
   sdk:0x0008e958 Sub000000000acf5958
   ??? Sub0000000000000000

Raw Request Data:
00000000   01 00 18 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  03 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.Nfc.Nfp.IUser.StartDetection(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nfc\Nfp\UserManager\IUser.cs:line 106
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### What's the issue you encountered?

Pressing some key combinations this error appears and game game execution and ryujinx ends

### How can the issue be reproduced?

Pressing random keys (quickly it fails faster)

### Environment?

- Ryujinx version: 1.0.5155
- Game version: 1.0.0
- System Specs:
  - OS: Fedora 32
  - CPU: i7-8650
  - GPU: Intel
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Using a PS3 controller mapped with:

```
{
  deadzone_left: 0,
  deadzone_right: 0,
  trigger_threshold: 0,
  left_joycon: {
    stick_x: Axis0,
    invert_stick_x: false,
    stick_y: Axis1,
    invert_stick_y: false,
    stick_button: Button10,
    button_minus: Button4,
    button_l: Button4,
    button_zl: Button6,
    button_sl: Unbound,
    button_sr: Unbound,
    dpad_up: Hat0Left,
    dpad_down: Hat0Left,
    dpad_left: Hat0Left,
    dpad_right: Hat0Right
  },  
  right_joycon: {
    stick_x: Axis2,
    invert_stick_x: false,
    stick_y: Axis3,
    invert_stick_y: false,
    stick_button: Button11,
    button_a: Button1,
    button_b: Button2,
    button_x: Button0,
    button_y: Button3,
    button_plus: Button5,
    button_r: Button5,
    button_zr: Button7,
    button_sl: Unbound,
    button_sr: Unbound
  },  
  index: 0,
  controller_type: JoyconPair,
  player_index: Player1
}
```

### PR DESCRIPTION
**Pull request by AcK77**
<div align="center">

<br /><i>Thanks to Kennisoan for the logo.</i><br /><br />
<a href="https://w.ryujinx.org/dl/2006"></a><br /><br />
</div>

All aboard the Amiibo train! 
As promised, this PR fulfills our commitment to provide Amiibo support once the Patreon goal was reached a month ago.

# How does it work?
We currently use a self hosted API (fork of https://github.com/N3evin/AmiiboAPI - big thanks to N3evin!) so you don't have to provide any Amiibo dumps. The benefit of using this API is being able to use all available Amiibo and associated information & images.
Once the game asks for an Amiibo scan, you can go to menu `Options` > `Scan an Amiibo`. A window will pop-up which lets you select the Amiibo you want (thanks to Xpl0itR for the orignal window code).

Amiibo1

As you can see, there is a checkbox to allow scanning the same Amiibo more than once per day. And did we mention that writable Amiibo is supported as well? That's right, not only will you be able to use Amiibo for exclusive content in your favorite games, but you can now train your Amiibo in Super Smash Bros. Ultimate! To do that, I've introduced a Virtual Amiibo JSON file which contains all generated data needed for this function.
This current implementation does not support Amiibo raw dump, as it is redundant & unnecessary. But, support for this may be added in the future.

Amiibo2
Amiibo3
Amiibo4
Amiibo5

Please test all Amiibo features in as many games as possible, and let us know how it's working in the comments or on Discord. 

Note to other devs:
- Fixes #1472
- The service part is checked by RE.
~~- There is a little surprise yet to come before this PR is ready to merge.~~

Amiibo6
Amiibo7
Amiibo8

### CODE REVIEW

**Comment by jduncanator** [comment]
Marking as draft until final changes are committed to avoid an accidental merge :)

**Comment by Thog** [comment]
I don't think there will be accidental merge here @jduncanator considering 2 reviews are required, undrafting

**Comment by Shahil-Ayato** [comment]
18D8B238-B206-4E2C-9D22-610C60B33002
I feel that the amiibo should have its own tab in top right or be put in the {Tools} tab

File: Ryujinx/Ui/Windows/AmiiboWindow.cs [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+            _randomUuidCheckBox.Sensitive = false;
+
+            _ = LoadContentAsync();
+        }
+
+        private async Task<bool> CheckConnectivity()
+        {
+            try
+            {
+                HttpResponseMessage response = await _httpClient.GetAsync("https://www.google.com/");
```
Comment (CeruleanSky) [inline Ryujinx/Ui/Windows/AmiiboWindow.cs:100]: Google might not be available everywhere and connecting to it doesn't mean you can connect to ryujinx.org. 
Perhaps:
`_httpClient.SendAsync(new HttpRequestMessage (HttpMethod.Head, "https://amiibo.ryujinx.org/"));`
To just read headers, thus making a light request on the ryujinx servers. 
Then the error message can say something along the lines of
`"Unable to connect to Amiibo information server, the service is down or check your internet connection"`

Comment (Benedani) [reply Ryujinx/Ui/Windows/AmiiboWindow.cs:100]: Checking for a different website when the Ryujinx ping failed could still differentiate between your internet and the service being down. Actually, why not just ping the web server instead of connecting to it?

Comment (CeruleanSky) [reply Ryujinx/Ui/Windows/AmiiboWindow.cs:100]: > Actually, why not just ping the web server instead of connecting to it?

Pinging is light and would let you know if your network stack can communicate with the network stack of the machine whose ip address is resolved, but wouldn't tell you if the amiibo.ryujinx.org http server is functioning and connectable , which is going to happen sooner or later if the ping works.

The suggestion checks your internet is working, can connect, the http server is connectable, and with the `last-modified` field can even let you know if you have the latest version all in one step.

>Checking for a different website when the Ryujinx ping failed could still differentiate between your internet and the service being down.

If needed, that would certainly help diagnose things after the failure.  But a proper website would need to be picked and so forth, instead I just suggested changing the error message to recommend the user (manually) check their internet or let them assume the server was down.

**Comment by GamerzHell9137** [comment]
Here's some issues and suggestions i'd like to give:

1. Hyrule Warriors crashes when Amiibo is chosen because of an unimplemented service
```00:01:41.113 |W| HLE.OsThread.5 KernelIpc CallMethod: Missing service Ryujinx.HLE.HOS.Services.Nfc.IUserManager: 0 ignored
```
2. I'd change the drop down list style to a text box style ala System TimeZone since some Amiibo series have way too many Amiibos (Animal Crossing) 
image
image

3. If not changed then the UI should be fixed, things above in the AC list is empty and it fills up the whole screen, vertically both above and under legit entries. example of empty lines above
image

4. A way to press a letter on keyboard so that the list drops down to that section of the list (again, for games that have way too many amiibos ;Animal Crossing)

**Comment by 6Fer6** [comment]
Works flawlessly on the following games: Super Mario Odyssey, Splatoon 2, Super Smash Bros Ultimate, Captain Toad: Treasure Tracker, Yoshi’s Crafted World and Mario Kart 8 Deluxe. But there are some issues with the GUI:
•	In Super Mario Odyssey, if you press the right dpad button it allows you to use amiibo, then press the Options button in Ryujinx it shows the ‘Scan an Amiibo’ in white, but if you release the right dpad button, the ‘Scan an Amiibo’ option is still clickable. (This is a limitation with GTK, but I was told to comment on the PR)
image
•	Currently every time you open the ‘Scan an Amiibo’ option it defaults to 8-Bit Mario. It would be a nice if you previously scanned a character, it would automatically appear the same character on the list again. This would be useful for games like Splatoon 2, where you must scan a character for a second time to add them as friends, and SSBU, where you must scan again to save all your training.
•	Move the button to the bar on the top, for easier access.  
image

**Comment by Jerr-z** [comment]
super smash bros does not recognize link amiibo, and attempting to edit the name for amiibo fighter will result in a crash

**Comment by EmulationFanatic** [comment]
> super smash bros does not recognize link amiibo, and attempting to edit the name for amiibo fighter will result in a crash

Confirmed both of these things, though the Link Amiibo issue is the only surprising one. Lack of custom user profile support is the reason for the name editing crash.

**Comment by Jerr-z** [comment]
another issue observed in smash ultimate is if you scan the amiibo from the amiibo menu and choose battle the amiibo, you cannot save the amiibo data after the battle because the game suggests that the data is overwritten

**Comment by komawoyo** [comment]
So if I'm out in the boonies without internet, this will not work?

**Review by Thog — APPROVED** [review]
lgtm

**Comment by PokemongamerEB** [comment]
Every time I try to use an amiibo in Smash Ultimate, the game crashes. Any idea why?

**Comment by PokemongamerEB** [comment]
> Every time I try to use an amiibo in Smash Ultimate, the game crashes. Any idea why?

Also if I need to send any info I will

**Comment by AcK77** [comment]
Come to our discord and contact on it, it will be easier than GitHub comments because we will need more informations for sure. Thanks.

**Comment by PokemongamerEB** [comment]
> Come to our discord and contact on it, it will be easier than GitHub comments because we will need more informations for sure. Thanks.

What's the discord?

**Comment by CeruleanSky** [comment]
> • In Super Mario Odyssey, if you press the right dpad button it allows you to use amiibo, then press the Options button in Ryujinx it shows the ‘Scan an Amiibo’ in white, but if you release the right dpad button, the ‘Scan an Amiibo’ option is still clickable. (This is a limitation with GTK, but I was told to comment on the PR)

To add to the above comment about Mario Odyssey, at least for me in win 10, if you are using keyboard for input, you can't click on the menu at all.  I held the right arrow key to open the amiibo scan prompt inside the game, and I could no longer use the Ryujinx toolbar.

**Comment by Mou-Ikkai** [comment]
Can .bin support be added? Can be useful for when I want to use my previously trained SSBU amiibos on Ryujinx.

**Comment by jduncanator** [comment]
> Can .bin support be added? Can be useful for when I want to use my previously trained SSBU amiibos on Ryujinx.

It was outlined in the PR description that this isn't a priority or a target for this specific PR, however anyone is free to add that functionality in the future.

**Comment by CeruleanSky** [comment]
> Can .bin support be added? Can be useful for when I want to use my previously trained SSBU amiibos on Ryujinx.

From the opening post "This current implementation does not support Amiibo raw dump, as it is redundant & unnecessary. But, support for this may be added in the future." , 

I suppose the discord would have the latest info, gbatemp has some forks of emuiibo that can convert them, though there might be better utilities now.

**Comment by AcK77** [comment]
- Added a new Actions menu, under which the functions Stop Emulation, Simulate Wake-up Message and Scan an Amiibo have been moved.
unknown1

- Removed usage of Google to check connectivity. Instead it now uses the "last-modified" header instead (suggested by @CeruleanSky).
- Only Amiibo related to the currently running game are shown, along with a pertinent usage description and indicator of whether the Amiibo is writable.
  - Added a checkbox option to show all Amiibo if the user wishes.
  unknown2

- Added a message dialog when the Amiibo scanning isn't available in guest game (Fixes SMO DPad issue, reported by @6Fer6).
- The last scanned Amiibo is now stored at each game execution, which eases use of scanning writable Amiibo (suggested by @6Fer6).
- Fixed Amiibo ID format: now every Amiibo should be recognized properly (Fixes SSBU issue, reported by @Jerr-z).
  unknown3


@GamerzHell9137 Those extra spaces in the dropdown menus are due to a GTK issue and I'll not change it to something else. The list is already reduced now.

Hyrule Warriors crashes when Amiibo is chosen because of an unimplemented service isn't fixed for now, it will maybe fixed once this PR is merged.
```
00:01:41.113 |W| HLE.OsThread.5 KernelIpc CallMethod: Missing service Ryujinx.HLE.HOS.Services.Nfc.IUserManager: 0 ignored
```

@Jerr-z I'm not able to reproduce this issue:
```
another issue observed in smash ultimate is if you scan the amiibo from the amiibo menu and choose battle the amiibo, you cannot save the amiibo data after the battle because the game suggests that the data is overwritten
```

I'd want to add Emuiibo files support (as a surprise), Ryujinx currently got a license exemption from XorTroll (https://github.com/XorTroll/emuiibo/commit/a442cc117bf1279e56446c15884d656e91a71c59), Thanks to him.
But this take time to implement and I don't want to block this PR anymore so it will be implemented later.

**Review by Thog — APPROVED** [review]

**Comment by stromcon** [comment]
Hey there,

tried on MK8 working fine !

Capture_decran_2021-03-13_132637
Capture_decran_2021-03-13_132556

But on FE, when pressing "scan it!" button nothing happens, even with hack checkbox. game is not crashing, we can go back by pressing B and console logs are not reporting anything. Here is the video with the test on FE (using discord link because MP4 is > 10 Mb) : https://discord.com/channels/410208534861447168/814263228926132274/820279075036725288

Thanks for your work !

**Comment by makaragamz** [comment]
Sorry but I may be missing something. I tried both Downloading the latest release from the website and also build the master branch (dirty) but I still have no option for Loading Amiibos in the Options menu, do I have to do any additional step?

**Comment by EmulationFanatic** [comment]
@makaragamz it's in the new Actions menu as shown here https://github.com/Ryujinx/Ryujinx/pull/2006#issuecomment-797829812

**Comment by makaragamz** [comment]
> @makaragamz it's in the new Actions menu as shown here [#2006 (comment)](https://github.com/Ryujinx/Ryujinx/pull/2006#issuecomment-797829812)

Oh I'm terribly sorry, didn't notice that comment, I just tried from there and its working fine, thank you very much! I will keep testing this feature, where can I share my feedback on its functionality? I'd like to help with my findings

**Comment by HarshNarayanJha** [comment]
It says Unable to connect to API server, and I have Internet connection and even tried with firewall disabled.

**Comment by M3morize0104** [comment]
Sorry, it's not clear to me how I'm supposed to install this. I'm not a programmer or anything like that, could you explain in a more general and simple way the steps?

**Comment by AcK77** [comment]
https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#amiibo-emulation
