### PR TITLE
Ava UI: Fix locale crash

### LINKED ISSUE #6382: [Bug] Ryujinx Avalonia GUI: Unhandled exception caught error
### Description of the issue

Unhandled exception caught error with new Ryujinx Avalonia GUI on Linux/Steam Deck.

### Reproduction steps

Not sure if this is a Steam Deck specific issue:

Update to Avalonia GUI on a Steam Deck
Launch Ryujinx using `Ryujinx.sh` in the `publish` folder in a terminal
See unhandled exception caught error

### Log file

(deck@steamdeck publish)$ ./Ryujinx.sh
00:00:00.008 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.093 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.105 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.106 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.107 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.108 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.110 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.110 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x163F
00:00:00.111 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.113 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.113 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.115 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.124 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.124 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.125 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.125 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.125 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.125 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.125 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.126 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.126 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.128 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.128 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.128 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.128 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.131 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.146 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1217
00:00:00.165 |N| Application Print: Operating System: SteamOS (X64)
00:00:00.165 |N| Application Print: CPU: AMD Custom APU 0932   AmdCcxVhFf3PeiInit Entry ; 8 logical
00:00:00.169 |N| Application Print: RAM: Total 14.5 GiB ; Available 11.3 GiB
00:00:00.177 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.178 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.252 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Ryujinx.Ava.Common.Locale.LocaleManager' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.Deserialize[T](String value, JsonTypeInfo`1 typeInfo) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 41
   at Ryujinx.Ava.Common.Locale.LocaleManager.LoadJsonLanguage(String languageCode) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 146
   at Ryujinx.Ava.Common.Locale.LocaleManager.LoadLanguage(String languageCode) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 134
   at Ryujinx.Ava.Common.Locale.LocaleManager.Load() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 54
   at Ryujinx.Ava.Common.Locale.LocaleManager..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 30
   at Ryujinx.Ava.Common.Locale.LocaleManager..cctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 21
   --- End of inner exception stack trace ---
   at Ryujinx.Ava.Common.Locale.LocaleManager.get_Instance() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 21
   at Ryujinx.Ava.UI.Windows.StyleableWindow..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/UI/Windows/StyleableWindow.cs:line 28
   at Ryujinx.Ava.UI.Windows.MainWindow..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 59
   at Ryujinx.Ava.App.OnFrameworkInitializationCompleted() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/App.axaml.cs:line 36
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Program.cs:line 51
Unhandled exception. System.TypeInitializationException: The type initializer for 'Ryujinx.Ava.Common.Locale.LocaleManager' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.Deserialize[T](String value, JsonTypeInfo`1 typeInfo) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 41
   at Ryujinx.Ava.Common.Locale.LocaleManager.LoadJsonLanguage(String languageCode) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 146
   at Ryujinx.Ava.Common.Locale.LocaleManager.LoadLanguage(String languageCode) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 134
   at Ryujinx.Ava.Common.Locale.LocaleManager.Load() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 54
   at Ryujinx.Ava.Common.Locale.LocaleManager..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 30
   at Ryujinx.Ava.Common.Locale.LocaleManager..cctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 21
   --- End of inner exception stack trace ---
   at Ryujinx.Ava.Common.Locale.LocaleManager.get_Instance() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Common/Locale/LocaleManager.cs:line 21
   at Ryujinx.Ava.UI.Windows.StyleableWindow..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/UI/Windows/StyleableWindow.cs:line 28
   at Ryujinx.Ava.UI.Windows.MainWindow..ctor() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 59
   at Ryujinx.Ava.App.OnFrameworkInitializationCompleted() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/App.axaml.cs:line 36
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Program.cs:line 51
Aborted (core dumped)
(134)(deck@steamdeck publish)$

### OS

Steam Deck/SteamOS

### Ryujinx version

1.1.1217

### Game version

_No response_

### CPU

_No response_

### GPU

_No response_

### RAM

_No response_

### List of applied mods

_No response_

### Additional context?

_No response_

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Fixes a crash on Ava when an invalid locale value is taken from system, or present in config.

Fixes #6382.

### CODE REVIEW

File: src/Ryujinx/Common/Locale/LocaleManager.cs [hunk 1]
```diff
@@ -30,28 +30,28 @@ public LocaleManager()
             Load();
         }
 
-        public void Load()
+        public bool IsRTL()
```
Comment (marysaka) [inline src/Ryujinx/Common/Locale/LocaleManager.cs:33]: Can you noot reorder function? that make the diff quite annoying to read

**Review by marysaka — APPROVED** [review]
otherwise lgtm

**Review by riperiperi — APPROVED** [review]

File: src/Ryujinx/Common/Locale/LocaleManager.cs [hunk 2]
```diff
@@ -30,28 +30,19 @@ public LocaleManager()
             Load();
         }
 
-        public void Load()
+        private void Load()
         {
-            // Load the system Language Code.
-            string localeLanguageCode = CultureInfo.CurrentCulture.Name.Replace('-', '_');
+            try
```
Comment (gdkchan) [inline src/Ryujinx/Common/Locale/LocaleManager.cs:35]: Why does it need this `try`/`catch`?

Comment (IsaacMarovitz) [reply src/Ryujinx/Common/Locale/LocaleManager.cs:35]: If the locale returned by `CultureInfo.CurrentCulture.Name` does not have a corresponding file, the function to load the JSON will error. try/catch is here to stop that from crashing us.

Comment (TSRBerry) [reply src/Ryujinx/Common/Locale/LocaleManager.cs:35]: Why aren't you checking if the file exists instead of using `try`/`catch`?

File: src/Ryujinx/Common/Locale/LocaleManager.cs [hunk 3]
```diff
@@ -30,28 +30,21 @@ public LocaleManager()
...
-            string localeLanguageCode = CultureInfo.CurrentCulture.Name.Replace('-', '_');
+            var localeLanguageCode = !string.IsNullOrEmpty(ConfigurationState.Instance.UI.LanguageCode.Value) ?
+                ConfigurationState.Instance.UI.LanguageCode.Value : CultureInfo.CurrentCulture.Name.Replace('-', '_');
 
-            // If the view is loaded with the UI Previewer detached, then override it with the saved one or default.
+            // Load en_US as default, if the target language translation is missing or incomplete.
+            LoadDefaultLanguage();
+            LoadLanguage(localeLanguageCode);
+
+            // Save whatever we ended up with
```
Comment (AcK77) [inline src/Ryujinx/Common/Locale/LocaleManager.cs:42]:
```suggestion
            // Save whatever we ended up with.
```

File: src/Ryujinx/Common/Locale/LocaleManager.cs [hunk 4]
```diff
@@ -30,28 +30,21 @@ public LocaleManager()
...
-                if (!string.IsNullOrEmpty(ConfigurationState.Instance.UI.LanguageCode.Value))
-                {
-                    localeLanguageCode = ConfigurationState.Instance.UI.LanguageCode.Value;
-                }
-                else
-                {
-                    localeLanguageCode = DefaultLanguageCode;
-                }
+                ConfigurationState.Instance.UI.LanguageCode.Value = _localeLanguageCode;
+                ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
```
Comment (AcK77) [inline src/Ryujinx/Common/Locale/LocaleManager.cs:46]:
```suggestion

                ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
```

File: src/Ryujinx/Common/Locale/LocaleManager.cs [hunk 5]
```diff
@@ -126,24 +119,42 @@ public string UpdateAndGetDynamicValue(LocaleKeys key, params object[] values)
...
 
-        private static Dictionary<LocaleKeys, string> LoadJsonLanguage(string languageCode = DefaultLanguageCode)
+        private static Dictionary<LocaleKeys, string> LoadJsonLanguage(string languageCode)
         {
             var localeStrings = new Dictionary<LocaleKeys, string>();
             string languageJson = EmbeddedResources.ReadAllText($"Ryujinx/Assets/Locales/{languageCode}.json");
+
+            if (languageJson == null)
+            {
+                // We were unable to find file for that language code
```
Comment (AcK77) [inline src/Ryujinx/Common/Locale/LocaleManager.cs:154]:
```suggestion
                // We were unable to find file for that language code.
```

**Review by AcK77 — CHANGES_REQUESTED** [review]

**Review by AcK77 — APPROVED** [review]
