### PR TITLE
Hide UI rework/arrow key fix

### LINKED ISSUE #2502: Left and right arrow keys brings up File menu after running the game
### What's the issue you encountered?
The arrow keys ← → on the keyboard keep bringing up the Ryujin menu at the top during gameplay, which causes a loss of control in any game. My workaround was to change the directional pads to a different set of keys, but I would rather go back to the arrow keys.

### How can the issue be reproduced?

1. Run any game.
2. Press the left and right arrow keys.

### Log file

[Ryujinx_1.0.6976_2021-07-24_14-59-00.log](https://github.com/Ryujinx/Ryujinx/files/6873118/Ryujinx_1.0.6976_2021-07-24_14-59-00.log)
[Ryujinx_1.0.6976_2021-07-24_15-19-44.log](https://github.com/Ryujinx/Ryujinx/files/6873127/Ryujinx_1.0.6976_2021-07-24_15-19-44.log)

### Environment?

- Ryujinx Version: 1.0.6976

- System Specs:
Operating System: Microsoft Windows 10.0.19042 (X64)
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz ; 8 logical
RAM: Total 16335 MB ; Available 10817 MB
NVIDIA Corporation NVIDIA GeForce GTX 1060 with Max-Q Design
- Applied Mods : [ romfs patch for audio ]

### PR DESCRIPTION
**Pull request by ooa113y**
This fixes #2502, which was a regression caused by #2411 (I'm sorry! 😅)

For one, Alt no longer focuses the menu bar (this is the part of my implementation that caused the issue). That functionality wasn't really relevant to the original intent of #2411, and the main purpose of the PR remains usable. Focus on Alt is something I might fix later, as I can't seem to figure out what broke it in the first place.

Secondly, this reworks the entire flow of how the "Show UI" hotkey works. Note that it is specifically a "Show UI" hotkey, and hiding the UI still has to be done via the Actions menu, as we don't want users to trigger it by accident (there was some relevant discussion in #2411).
1. It is now a legitimate entry in the `KeyboardHotkeys` struct, rather than being hacked on via `MainWindow`. Since we no longer need menubar access for this, this makes more sense.
2. The key is now configurable (via `Config.json`).
3. The key now defaults to F4. I found several annoyances with Alt, as it's part of the language-switching combination and also getting in the way of taking a (regular, non-Ryujinx) screenshot. Something that's not commonly used made more sense. Of course, due to the point 2 above, users are welcome to switch it back to Alt if they are so inclined.
4. The key is read from the config file at startup and inserted into the menu label so that the user is clear on the exact key that needs to be pressed, even if it's changed from the default. The user has to know how to bring the UI back.

Additionally, I ended up fixing a problem with the implementation of the `KeyboardHotkeyState` enum which would cause it to break were we to add any more hotkeys. The default values set here are 1, 2, 3 etc, so adding a third hotkey would make it automatically press the first two, as 1+2 would equal to 3. I switched the values to powers of 2, which is a safe approach for this kind of thing.

### CODE REVIEW

File: Ryujinx/Ui/RendererWidgetBase.cs [hunk 1]
```diff
@@ -596,9 +602,10 @@ private bool UpdateFrame()
         [Flags]
         private enum KeyboardHotkeyState
         {
-            None,
-            ToggleVSync,
-            Screenshot
+            None = 0,
+            ToggleVSync = 1,
+            Screenshot = 2,
+            ShowUi = 4
```
Comment (AcK77) [inline Ryujinx/Ui/RendererWidgetBase.cs:608]: Why not 3?

Comment (AcK77) [reply Ryujinx/Ui/RendererWidgetBase.cs:608]: Nvm it’s at the end of the description, maybe we should use a bit flag instead.

Comment (ooa113y) [reply Ryujinx/Ui/RendererWidgetBase.cs:608]: Isn't this what we're effectively doing here? Is there a better approach? Googling "C# bit flags" nets me a ton of results for the `[Flags]` attribute that we're using here and not much else at all.

Comment (gdkchan) [reply Ryujinx/Ui/RendererWidgetBase.cs:608]: > 
> 
> Nvm it’s at the end of the description, maybe we should use a bit flag instead.

The values are already power of 2, therefore they can already function as "bit flags". Maybe using `1 << 0`, `1 << 1` and `1 << 2` would be a bit more clear though (and it's what we do for other enums that are used as flags).

Comment (ooa113y) [reply Ryujinx/Ui/RendererWidgetBase.cs]: Adjusted.

**Review by Thog — APPROVED** [review]

**Review by AcK77 — APPROVED** [review]
