### PR TITLE
ui: Check last played datetime validity against current culture

### LINKED ISSUE #1727: Ryujinx crashes when sorting by last played (if not all games are played yet)
### What's the issue you encountered?

When you use Ryujinx with multiple games which you did not play yet, it will crash when pressing the last played section. This probably is because it will sort data that is not available, or because multiple games have not been played.
If you sort this way and then add multiple games in the game folder, you will be unable to open Ryujinx unless you remove the games again and sort by something else.
I use the latest master build

### How can the issue be reproduced?

- add multiple games which have not been played
- press 'last played' to sort on it

### Log file

[Ryujinx_2020-11-18_12-26-24.log](https://github.com/Ryujinx/Ryujinx/files/5559689/Ryujinx_2020-11-18_12-26-24.log)

### Environment?

- Ryujinx version: 1.0.5742</br>
- Game version: X.X.X</br>
- System Specs:
  - OS: *Windows 10 2004*
  - CPU: *i7 9750H*
  - GPU: *NVIDIA RTX 2070 (laptop)*
  - RAM: *16GB DDR4*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

### PR DESCRIPTION
**Pull request by Thog**
This is an issue happening when you change your datetime format on your system and try to sort via last played datetime.
DateTime.Parse use the current thread culture and will not parse date correctly, effectively causing a crash.

As such, I added a check when loading the game list that ensure that the datetime is valid in current culture.

Fix #1727.

### CODE REVIEW

**Review by AcK77 — APPROVED** [review]

File: Ryujinx/Ui/ApplicationLibrary.cs [hunk 1]
```diff
@@ -390,6 +390,13 @@ byte[] Read(long position, int size)
 
                 ApplicationMetadata appMetadata = LoadAndSaveMetaData(titleId);
 
+                if (appMetadata.LastPlayed != "Never" && !DateTime.TryParse(appMetadata.LastPlayed, out _))
+                {
+                    Logger.Warning?.Print(LogClass.Application, $"Last played datetime \"{appMetadata.LastPlayed}\" is invalid for current system culture, skipping (did current culture changed?)");
```
Comment (riperiperi) [inline Ryujinx/Ui/ApplicationLibrary.cs:395]: `did current culture change?` is better.

**Review by riperiperi — APPROVED** [review]

**Review by Xpl0itR — APPROVED** [review]
