### PR TITLE
Ava UI: Handle updates containing non numeric characters

### LINKED ISSUE #7021: [Bug] Update Manager can fail to list updates when an added update contains letters
### Description of the issue

I encountered a title update management bug when trying to apply a v1.1.8 update to Sonic Superstars.
The initial impression was that Ryujinx did not recognise the update, but removing a previously loaded update v1.0.5A would allow the newer updates to be listed.
From previous use cases, the expectation was that I'd be able to load all updates against the title and it should list all of them.

Judging by the log file, it appears that the version string ending in "5A" is not being handled correctly, possibly due to containing a letter as compared to the other updates which lack them.
This handling error has manifested in three different ways:

* Adding multiple updates at once can result in no updates being listed, if the v1.0.5A update is among them
* Adding v1.1.5 and/or v.1.1.8 updates will not display if v1.0.5A has been previously added, and will only display once v1.0.5A is removed
* Adding v1.0.5A whilst v1.1.5 and/or v1.1.8 updates have been previously added, will not display the v1.0.5A update and will cause Ryujinx to unexpectedly quit upon removing either v1.1.5 or v1.1.8

### User data
* `Sonic Superstars [01008F701C074000][v0].xci` file dumped from game card using homebrew'd Switch + [nxdumptool](https://github.com/DarkMatterCore/nxdumptool/releases)
   * xci file does not include any update NSP
* `Sonic Superstars [01008F701C074800][v131072][UPD].nsp` - contains v1.0.5A
   * Will have been dumped using nxdumptool [v1.1.15](https://github.com/DarkMatterCore/nxdumptool/releases/tag/v1.1.15) from Feb 2022 
* `Sonic Superstars 1.1.5 [01008F701C074800][v262144][UPD].nsp`
* `Sonic Superstars 1.1.8 [01008F701C074800][v327680][UPD].nsp`
    * v1.1.5 and v1.1.8 updates will have been dumped using [nxdumptool-rewrite (latest commit build)](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease)
* Ryujinx build v1.1.1345

### Steps to reproduce
* Launch Ryujinx and locate the game title from the games list
* Right-click and select "Manage Title Updates" to open the title's Update Manager modal
* Click "Add" and use file dialogue to add all three update NSP files
   * Ryujinx's Update Manager will not list any updates, and gives no response message
* Click Add and use file dialogue to add the v1.0.5a update NSP file
    * Ryujinx's Update Manager will list "Version 1.0.5A"
* Whilst Version 1.0.5A is listed, add the v1.1.5 and/or v1.1.8 NSP files
    * Ryujinx's Update Manager gives no response message and continues to only display "Version 1.0.5A"
* Click the Cross button next to "Version 1.0.5A" to remove the update
    * Ryujinx's Update Manger will now display the Version 1.1.5 and Version 1.1.8 updates that were added
* Whilst Versions 1.1.5 and 1.1.8 are listed, re-add the v1.0.5A NSP
    * Ryujinx's Update Manager gives no response message and continues to only display Versions 1.1.5 and 1.1.8
* Click the Cross button next to "Version 1.1.5" or "Version 1.1.8" to remove the update
    * Ryujinx will unexpectedly quit with an `System.InvalidOperationException` error written to log file.

### Video demo
https://github.com/user-attachments/assets/1a2650a2-a41a-4121-938b-2b3d8904aa8b

### Log file
[Ryujinx_1.1.1345_2024-07-12_16-35-38.log](https://github.com/user-attachments/files/16196477/Ryujinx_1.1.1345_2024-07-12_16-35-38.log)

### Log excerpt
```
00:00:29.735 |E| Application : Unhandled exception caught: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: The input string '5A' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1)
   at System.Number.ThrowOverflowOrFormatException[TChar,TInteger](ParsingStatus, ReadOnlySpan`1)
   at System.Number.ParseBinaryInteger[TChar,TInteger](ReadOnlySpan`1, NumberStyles, NumberFormatInfo)
   at System.Int32.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at System.Version.TryParseComponent(ReadOnlySpan`1, String, Boolean, Int32& )
   at System.Version.ParseVersion(ReadOnlySpan`1, Boolean)
   at System.Version.Parse(String)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.<>c.<SortUpdates>b__24_0(TitleUpdateModel first, TitleUpdateModel second) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 141
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1, Comparison`1, Int32, Int32)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1, Int32, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   at System.Collections.Generic.List`1.Sort(Comparison`1)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.SortUpdates() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 129
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.RemoveUpdate(TitleUpdateModel update) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 204
   at Ryujinx.Ava.UI.Windows.TitleUpdateWindow.RemoveUpdate(Object sender, RoutedEventArgs e) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\TitleUpdateWindow.axaml.cs:line 93
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object, RoutedEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 52
```

### OS

Windows 10 v22H2

### Ryujinx version

1.1.1345

### Game version

n/a

### CPU

Intel Core i7-12700K

### GPU

NVIDIA RTX 3070

### RAM

32GB DDR5 (2x16GB)

### List of applied mods

_No response_

### Additional context?

Not an emulation issue; front-end update management issue.

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Fixes #7021.

image

### CODE REVIEW

File: src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs [hunk 1]
```diff
@@ -135,17 +135,23 @@ public void SortUpdates()
...
                 }
 
-                if (string.IsNullOrEmpty(second.Control.DisplayVersionString.ToString()))
+                if (string.IsNullOrEmpty(secondVersionString))
                 {
                     return 1;
                 }
 
-                return Version.Parse(first.Control.DisplayVersionString.ToString()).CompareTo(Version.Parse(second.Control.DisplayVersionString.ToString())) * -1;
+                var firstVersion = Version.Parse(firstVersionString.Where(x => char.IsDigit(x) || x != '.').ToArray());
```
Comment (lostromb) [inline src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs:151]: I think a regex with capture groups would be more effective than this weird LINQ construct. `(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:\.(\d+))?` would match version strings with up to 4 numerical groups.

Comment (IsaacMarovitz) [reply src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs]: A regex would be way too expensive

**Comment by RupeeClock** [comment]
Tested Win_x64 artifact build Ryujinx 1.1.0+f5b28e3 from above and fix looks correct.
Am able to add all three updates to the title without issue, including the update with the alphanumeric version number 1.0.5a
image

Other XCI titles with bundled updates also worked correctly, when adding other updates.

File: src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs (hunk 1 above)
Comment (lostromb) [reply src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs]: maybe that would a separate code fix. it also bugs me that the parsing code is duplicated twice instead of just being its own function

**Review by riperiperi — APPROVED** [review]
Makes sense, though I imagine the case where there is `1.1.0a` and `1.1.0b` could break this comparison.

**Review by TSRBerry — CHANGES_REQUESTED** [review]
This solution seems like a band-aid to me. Ignoring all characters except digits is the wrong approach for this.

Is there a reason we aren't just using string comparison for this?
It seems to work pretty well: https://dotnetfiddle.net/08WM86

**Comment by IsaacMarovitz** [comment]
> This solution seems like a band-aid to me. Ignoring all characters except digits is the wrong approach for this.
> 
> Is there a reason we aren't just using string comparison for this? It seems to work pretty well: https://dotnetfiddle.net/08WM86

Your approach seems to work so I'll switch to it.

**Comment by TSRBerry** [comment]
Without verifying it, I think GTK probably also did string comparison that's why I asked about it.

**Review by TSRBerry — DISMISSED** [review]
Lgtm, thank you for using my suggestion!

**Comment by RupeeClock** [comment]
Quickly tested artefact [ryujinx-Release-1.1.0+c36dd97-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/1719924876.zip) and worked correctly for me.

**Comment by lostromb** [comment]
Wait, if we switch to string comparison, won't that mess up sorting of versions that are longer than 1 digit long? I thought that's why we were doing `Version.Parse` so it does a proper piecewise comparison of major, minor, sub components.

Naive string comparison would result in weird orderings like this:
`1.0.0` < `1.10.0` < `1.5.1`

**Comment by TSRBerry** [comment]
Yeah, it definitely doesn't work for everything (see: https://dotnetfiddle.net/5cuTTz). Thanks for noticing that!

I guess our best bet is regex then.

**Review by TSRBerry — CHANGES_REQUESTED** [review]
Since the string comparison doesn't work for everything, we can't use it.

We should probably switch to regex.

**Comment by lostromb** [comment]
There's the new AOT way of doing regexes that I haven't learned yet but this would probably do the job, plus it'd be unit testable.
```csharp
private static readonly Regex VersionParseRegex = new Regex("(\\d+)(?:\\.(\\d+))?(?:\\.(\\d+))?(?:\\.(\\d+))?");

internal static Version ParseVersionString(string str)
{
    int major = 0;
    int minor = 0;
    int build = 0;
    int revision = 0;
    Match match = VersionParseRegex.Match(str);
    if (!match.Success)
    {
        return new Version();
    }

    major = int.Parse(match.Groups[0].Value);
    if (match.Groups[1].Success)
    {
        minor = int.Parse(match.Groups[1].Value);
        if (match.Groups[2].Success)
        {
            build = int.Parse(match.Groups[2].Value);
            if (match.Groups[3].Success)
            {
                revision = int.Parse(match.Groups[3].Value);
            }
        }
    }

    return new Version(major, minor, build, revision);
}
```

**Comment by gdkchan** [comment]
Is there any constraint on the version strings? Like, can we assume they will be formatted in a specific way? If not, we should probably just some sort of string based sort with some best effort to parse the numbers there.

**Comment by gdkchan** [comment]
There's a integer version number here already: https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.HLE/FileSystem/ContentMetaData.cs#L20
It should probably be using that for parsing purposes. In fact, doing so is even simpler than the current change, one just needs to modify `TitleUpdateViewModel.AddUpdate` and `TitleUpdateModel` to include that version. Then the compare is as simple as comparing two integers values.

I did not test this myself though. I don't have many updates, and it seems that a regression is preventing me from adding my complete games folder since a invalid file among them is now causing the emulator to crash.

**Comment by IsaacMarovitz** [comment]
> There's an integer version number here already

Nice catch, seems to work

**Comment by TSRBerry** [comment]
> I did not test this myself though. I don't have many updates, and it seems that a regression is preventing me from adding my complete games folder since a invalid file among them is now causing the emulator to crash.

Just review #7046 :p

**Comment by gdkchan** [comment]
Needs a rebase.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks, but I don't have any game with non-numeric characters in the version. I did test in a game where I have many different versions here, and it appears to be working properly. It shows the latest version in the top (after "No updates"), and older versions in the bottom, but I guess that's intentional.

File: src/Ryujinx/UI/Models/TitleUpdateModel.cs [hunk 2]
```diff
@@ -1,21 +1,20 @@
...
-            Control.DisplayVersionString.ToString()
-        );
-
-        public TitleUpdateModel(ApplicationControlProperty control, string path)
+        public TitleUpdateModel(uint version, string displayVersion, string path)
         {
-            Control = control;
+            Version = version;
+            Label = LocaleManager.Instance.UpdateAndGetDynamicValue(
+                System.IO.Path.GetExtension(path)?.ToLower() == ".xci" ? LocaleKeys.TitleBundledUpdateVersionLabel : LocaleKeys.TitleUpdateVersionLabel,
```
Comment (gdkchan) [inline src/Ryujinx/UI/Models/TitleUpdateModel.cs:15]: Add `using System.IO;`?

Comment (TSRBerry) [reply src/Ryujinx/UI/Models/TitleUpdateModel.cs:15]: If you omit the `System.IO` part it'll try to access the `Path` property.

**Review by TSRBerry — APPROVED** [review]
Lgtm!
