### PR TITLE
Miria: The Death of OpenTK 3

### LINKED ISSUE #1098: Controller don’t support hot-swapping
Or, in other words, hot-swapping doesn't seem to be supported. At the very least I would like to be able to start up the emu without having to worry about turning on the controller beforehand.

Related to this would be making sure that controller disconnects don't require an emulator restart, and allowing new controllers (players) to join in the middle of a game.

I'm not actually using an Xbox controller, this is DS4 using DS4Windows so they may be some discrepancies in how the XInput layer is accessed. But I do have various controllers I can test with.

### LINKED ISSUE #1465: Pro Controller right analog stick not recognized in <Controller Settings> without BetterJoy
## Bug Report

Pro Controller right analog stick axis not recognized in Controller Settings when using Steam drivers.
Recognized in all other programs including Dolphin, Yuzu, MS Wireless GamePad Properties, etc.
I personally think it's worth looking into for best compatibility.

### What's the issue you encountered?

Pro Controller right analog stick axis not recognized in Controller Settings when using Steam drivers.

### How can the issue be reproduced?

Use a Pro Controller set up using Steam

Options 
-> Settings 
-> Input 
-> [Player 1] Configure 
-> RStick (Lt/Rt)/(Up/Dn) Unbound 
-> Move right control stick in any direction
-> Nothing happens

Note: All other buttons work including HOME, Screen Capture, and Right Stick click down

### Log file

[N/A]

### Environment?

- Ryujinx version: 1.0.5142</br>
- System Specs:
  - OS:  Windows 10
  - CPU: i7-8750H
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : No

### LINKED ISSUE #1978: Native Gamecube Controller Support
#### Overview:
A "native" implementation for Gamecube controllers. The end result of this feature would allow users to simply plug their Gamecube controllers in and Ryujinx would automatically map default input bindings to that controller. At the moment, Some gamecube adapters are usable with Ryu, for example the [Nintendo Gamecube controller adapter](https://www.amazon.com/GameCube-Controller-Adapter-Nintendo-Switch/dp/B07DJX3ZR8/), or the [Mayflash adapter](https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Switch/dp/B00RSXRLUE) which can be set to a "PC" mode which works but requires the user to then manually set up controls and controller profiles and such. If your adapter doesn't have that, using an external program that produces xinput for ryu to read is the only option.
Ideally, one would be able to use the other mode, which is what is used when using the adapter with a Wii U or Switch. 

#### Smaller Details: 
In an ideal world, this implementation would also support things like:
- hotplugging (being able to plug in a controller while the emulator is running and it would properly detect/handle it)
- HID implementation (games like Smash would detect that the current input device is a gamecube controller, as opposed to a pro controller or something)
- Analog triggers...?

#### Nature of Request:  
 I _believe_ both Yuzu and Dolphin currently have a native gamecube controller implementation under the GPLv2+ license, both using libusb. (Don't take my word for it though, obviously)

### Why would this feature be useful?
The majority of the use cases apply to people looking to play Super Smash Brothers Ultimate, as that audience widely uses Gamecube controllers as their preferred peripheral of choice. Making it easier to use for that audience would make lots of people more comfortable navigating/using the emulator.

### LINKED ISSUE #2071: Lag every time i connect Nintendo Joycon
### What's the issue you encountered?
Starting every game without Nintendo joycons (via bluetooth) all works correctly and smothly.
If i just connect one Joycon games become super laggy from 60 to 10 fps every game.
If i just disconnect all joycons the game returns normally.

### How can the issue be reproduced?
Just connect a Joycon.

I've tried without success:
- Connect and disconnects joycons in game.
- Connect and disconnects joycons and restart game or Ryujinx.
- Restart pc.

Just to know: if i use another emulator it works without lag.

### Log file
[Ryujinx_1.0.0-dirty_2021-02-28_18-12-38.zip](https://github.com/Ryujinx/Ryujinx/files/6057381/Ryujinx_1.0.0-dirty_2021-02-28_18-12-38.zip)

### Environment?

- Ryujinx version: 1.0.0.dirty compiled just via github</br>
- System Specs:
  - OS: Linux-Manjaro
  - CPU: i5-7500
  - GPU: NVIDIA 980
  - RAM: 32gb
- Applied Mods : No

### Additional context?

n/a

Thx in advance. I hope my report will help someone.

### PR DESCRIPTION
**Pull request by Thog**
As a preparation for the new UI system and for Vulkan, this PR removes OpenTK 3 dependency entirely.

To do so, a new input system was implemented for keyboard and controller handling. On the controller side, SDL2 was chosen and handling of controllers was completely revisited.

With this new input system the following new features are now available:
- Controllers can now be hot-plugged without any constraints. No need to click any "refresh" buttons.
- Motion is supported without the need of external tools on supported controllers. (Legacy Cemuhook integration is still present if desired)
- Rumble API is exposed **while still not in use for now** (outside the scope of this PR)
- DS4, DS5, Pro Controller and Single Joycons are natively supported. (Joycon pairs are not yet natively supported and outside the scope of this PR; Cemuhook integration can be used for joycon pairs in the meantime.)
- GTK3 keyboard introduces support for different regional layouts.
- When a gamepad isn't supported by SDL2, a user can extend compatibility and mappings via the addition of a ``SDL_GameControllerDB.txt`` file in the same directory as ``Ryujinx.exe``. See [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) for community efforts.

As the nature of these changes are highly incompatible with (and impossible to migrate from) the old system, this will reset input configurations.

Changelog:
- Switch to OpenTK 4 for OpenAL implementation and mark OpenAL implementation as obsolete.
- Switch to OpenTK 4 for the Ryujinx.Graphics.OpenGL project.
- Use [SPB](https://github.com/Thog/SPB) for context creation and manipulations instead of OpenTK 3.
   - Currently only WGL and GLX backend are supported. (no regressions compared to old implementation)
- Switch to SDL2 for controller input.
- Switch to GTK3 for keyboard input.
- Individual keyboard support was removed.

Fixes #1465, Fixes #1098, Fixes #2071, Fixes #1978

### CODE REVIEW

**Comment by Ghostotakoi** [comment]
Plans for native mouse support

File: Ryujinx/Input/GTK3/GTK3Keyboard.cs [hunk 1]
```diff
@@ -0,0 +1,198 @@
+﻿using Ryujinx.Common.Configuration.Hid;
+using Ryujinx.Common.Configuration.Hid.Keyboard;
+using System;
+using System.Collections.Generic;
+using System.Numerics;
+using ConfigKey = Ryujinx.Common.Configuration.Hid.Key;
+
+namespace Ryujinx.Input.GTK3
```
Comment (SutandoTsukai181) [inline Ryujinx/Input/GTK3/GTK3Keyboard.cs:8]: `Ryujinx.Input.GTK3` is in a folder in `Ryujinx` project instead of in its own project or inside `Ryujinx.Input`. Is this intentional?

Comment (Thog) [reply Ryujinx/Input/GTK3/GTK3Keyboard.cs:8]: This is tied to GTK3 and the UI itself, there is no need of moving it as it's not code that can be shared across UIs.

File: Ryujinx.Common/Configuration/Hid/Controller/Motion/StandardMotionConfigController.cs [hunk 2]
```diff
@@ -0,0 +1,12 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace Ryujinx.Common.Configuration.Hid.Controller.Motion
+{
+    public class StandardMotionConfigController : MotionConfigController
```
Comment (AcK77) [inline Ryujinx.Common/Configuration/Hid/Controller/Motion/StandardMotionConfigController.cs:9]:
```suggestion
    public class StandardMotionConfigController : MotionConfigController { }
```

File: Ryujinx.Common/Configuration/Hid/Controller/StandardControllerInputConfig.cs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+﻿namespace Ryujinx.Common.Configuration.Hid.Controller
+{
+    public class StandardControllerInputConfig : GenericControllerInputConfig<GamepadInputId, StickInputId>
```
Comment (AcK77) [inline Ryujinx.Common/Configuration/Hid/Controller/StandardControllerInputConfig.cs:3]:
```suggestion
    public class StandardControllerInputConfig : GenericControllerInputConfig<GamepadInputId, StickInputId> { }
```

File: Ryujinx.Common/Configuration/Hid/Keyboard/StandardKeyboardInputConfig.cs [hunk 4]
```diff
@@ -0,0 +1,6 @@
+﻿namespace Ryujinx.Common.Configuration.Hid.Keyboard
+{
+    public class StandardKeyboardInputConfig : GenericKeyboardInputConfig<Key>
```
Comment (AcK77) [inline Ryujinx.Common/Configuration/Hid/Keyboard/StandardKeyboardInputConfig.cs:3]:
```suggestion
    public class StandardKeyboardInputConfig : GenericKeyboardInputConfig<Key> { }
```

File: Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+            _widget.KeyReleaseEvent += OnKeyRelease;
+        }
+
+        public string DriverName => "GTK3";
+
+        private static readonly string[] _keyboardIdentifers = new string[1] { "0" };
+
+        public ReadOnlySpan<string> GamepadsIds => _keyboardIdentifers;
+
+        public event Action<string> OnGamepadConnected;
```
Comment (AcK77) [inline Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs:30]: Could be nice to fix those warnings

File: Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+using System.Collections.Generic;
+using GtkKey = Gdk.Key;
+
+namespace Ryujinx.Input.GTK3
+{
+    public class GTK3KeyboardDriver : IGamepadDriver
+    {
+        private readonly Widget _widget;
+        private HashSet<GtkKey> _pressedKeys;
+
```
Comment (AcK77) [inline Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs:13]: remove extra empty line

File: Ryujinx/Ui/GLRenderer.cs [hunk 7]
```diff
@@ -245,7 +247,7 @@ protected override bool OnConfigureEvent(EventConfigure evnt)
 
         public void Start()
         {
-            IsRenderHandler = true;
+            // IsRenderHandler = true;
```
Comment (AcK77) [inline Ryujinx/Ui/GLRenderer.cs:250]: Why don't remove it?

File: Ryujinx/Ui/GLRenderer.cs [hunk 8]
```diff
@@ -742,5 +611,25 @@ private bool UpdateFrame()
...
             return true;
         }
+
+        [Flags]
+        private enum KeyboardHotkeyState
+        {
+            None,
+            ToggleVSync,
+        }
+
```
Comment (AcK77) [inline Ryujinx/Ui/GLRenderer.cs:621]: remove extra empty line

File: Ryujinx/Ui/GLRenderer.cs [hunk 9]
```diff
@@ -742,5 +611,25 @@ private bool UpdateFrame()
 
             return true;
         }
+
+        [Flags]
+        private enum KeyboardHotkeyState
+        {
+            None,
+            ToggleVSync,
```
Comment (AcK77) [inline Ryujinx/Ui/GLRenderer.cs:619]:
```suggestion
            ToggleVSync
```

File: Ryujinx/Ui/GLWidget.cs [hunk 10]
```diff
@@ -0,0 +1,117 @@
...
+            Initialized?.Invoke(this, EventArgs.Empty);
+        }
+
+        protected override void Dispose(bool disposing)
+        {
+            // Try to bind the OpenGL context before calling the shutdown event
+            try
+            {
+                OpenGLContext?.MakeCurrent(NativeWindow);
+            } catch (Exception) {}
```
Comment (AcK77) [inline Ryujinx/Ui/GLWidget.cs:103]:
```suggestion
            }
            catch (Exception) { }
```

File: Ryujinx/Ui/SPBOpenGLContext.cs [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+        public void MakeCurrent()
+        {
+            _context.MakeCurrent(_window);
+        }
+
+        public static SPBOpenGLContext CreateBackgroundContext(OpenGLContextBase sharedContext)
+        {
+            OpenGLContextBase context = PlatformHelper.CreateOpenGLContext(FramebufferFormat.Default, 3, 3, OpenGLContextFlags.Compat, true, sharedContext);
+            NativeWindowBase window = PlatformHelper.CreateWindow(FramebufferFormat.Default, 0, 0, 100, 100);
+            // window.Hide();
```
Comment (AcK77) [inline Ryujinx/Ui/SPBOpenGLContext.cs:38]: leftover?

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 12]
```diff
@@ -263,8 +377,7 @@ private void SetControllerSpecificFields()
 
         private void ClearValues()
         {
-            _lStickX.Label                    = "Unbound";
-            _lStickY.Label                    = "Unbound";
+            _lStick.Label                    = "Unbound";
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:380]:
```suggestion
            _lStick.Label                     = "Unbound";
```

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 13]
```diff
@@ -279,8 +392,7 @@ private void ClearValues()
             _zL.Label                         = "Unbound";
             _lSl.Label                        = "Unbound";
             _lSr.Label                        = "Unbound";
-            _rStickX.Label                    = "Unbound";
-            _rStickY.Label                    = "Unbound";
+            _rStick.Label                    = "Unbound";
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:395]:
```suggestion
            _rStick.Label                     = "Unbound";
```

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 14]
```diff
@@ -300,6 +412,7 @@ private void ClearValues()
             _controllerTriggerThreshold.Value = 0;
             _mirrorInput.Active               = false;
             _enableMotion.Active              = false;
+            _enableCemuHook.Active           = false;
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:415]:
```suggestion
            _enableCemuHook.Active            = false;
```

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 15]
```diff
@@ -396,14 +500,20 @@ private void SetValues(InputConfig config)
...
-                    _sensitivity.Value                = controllerConfig.Sensitivity;
-                    _gyroDeadzone.Value               = controllerConfig.GyroDeadzone;
-                    _enableMotion.Active              = controllerConfig.EnableMotion;
-                    _mirrorInput.Active               = controllerConfig.MirrorInput;
-                    _dsuServerHost.Buffer.Text        = controllerConfig.DsuServerHost;
-                    _dsuServerPort.Buffer.Text        = controllerConfig.DsuServerPort.ToString();
+                    _sensitivity.Value                = controllerConfig.Motion.Sensitivity;
+                    _gyroDeadzone.Value               = controllerConfig.Motion.GyroDeadzone;
+                    _enableMotion.Active              = controllerConfig.Motion.EnableMotion;
+                    _enableCemuHook.Active           = controllerConfig.Motion.MotionBackend == MotionInputBackendType.CemuHook;
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:506]:
```suggestion
                    _enableCemuHook.Active            = controllerConfig.Motion.MotionBackend == MotionInputBackendType.CemuHook;
```

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 16]
```diff
@@ -442,120 +552,144 @@ private InputConfig GetValues()
...
+                Enum.TryParse(_plus.Label,         out ConfigGamepadInputId rButtonPlus);
+                Enum.TryParse(_r.Label,            out ConfigGamepadInputId rButtonR);
+                Enum.TryParse(_zR.Label,           out ConfigGamepadInputId rButtonZr);
+                Enum.TryParse(_rSl.Label,          out ConfigGamepadInputId rButtonSl);
+                Enum.TryParse(_rSr.Label,          out ConfigGamepadInputId rButtonSr);
 
                 int.TryParse(_dsuServerPort.Buffer.Text, out int port);
 
-                return new ControllerConfig
+
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:633]: Remove extra empty line

File: Ryujinx/Ui/Windows/ControllerWindow.cs [hunk 17]
```diff
@@ -847,19 +1061,12 @@ private void ProfileLoad_Activated(object sender, EventArgs args)
                 {
                     using (Stream stream = File.OpenRead(path))
                     {
-                        config = JsonHelper.Deserialize<ControllerConfig>(stream);
+                        config = JsonHelper.Deserialize<InputConfig>(stream);
                     }
                 }
                 catch (JsonException)
```
Comment (AcK77) [inline Ryujinx/Ui/Windows/ControllerWindow.cs:1067]:
```suggestion
                catch (JsonException) { }
```

File: Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs [hunk 18]
```diff
@@ -1,27 +1,31 @@
...
 using System;
 using System.Collections.Generic;
+using System.Linq;
 using System.Threading;
 using static Ryujinx.Audio.Integration.IHardwareDeviceDriver;
 
 namespace Ryujinx.Audio.Backends.OpenAL
 {
+    // Planned for removal after SoundIO is supported with all sound devices.
+    [Obsolete]
```
Comment (AcK77) [inline Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs:14]: I'm not sure about the usage of this flag, as you can see in your PR, github print some warning about it, which is a bit annoying for review. (Even if I'm agree with what's planned)

**Review by AcK77 — CHANGES_REQUESTED** [review]

File: Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs [hunk 19]
```diff
@@ -0,0 +1,79 @@
...
+        private static MotionInputBackendType GetMotionInputBackendType(ref Utf8JsonReader reader)
+        {
+            // Temporary reader to get the backend type
+            Utf8JsonReader tempReader = reader;
+
+            MotionInputBackendType result = MotionInputBackendType.Invalid;
+
+            while (tempReader.Read())
+            {
+                // NOTE: We scan all properties ignoring the depth entirely in purpose.
```
Comment (Shahil-Ayato) [inline Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs:18]: Shouldn’t this be `on purpose`?

File: Ryujinx.Input/Assigner/ButtonAssigner.cs [hunk 20]
```diff
@@ -0,0 +1,36 @@
+namespace Ryujinx.Input.Assigner
+{
+    /// <summary>
+    /// An interface that allows to gather the driver input info to assign to a button on the UI.
+    /// </summary>
+    public interface ButtonAssigner
```
Comment (emmauss) [inline Ryujinx.Input/Assigner/ButtonAssigner.cs:6]: Shouldn't this use standard naming conventions for Interfaces? With an initial `I`

File: Ryujinx.Input/Assigner/GamepadButtonAssigner.cs [hunk 21]
```diff
@@ -0,0 +1,230 @@
...
+        public bool HasAnyButtonPressed()
+        {
+            return _detector.HasAnyButtonPressed();
+        }
+
+        public bool ShouldCancel()
+        {
+            // TODO: keyboard cancel
+            return _gamepad == null || !_gamepad.IsConnected;
+            // return Mouse.GetState().IsAnyButtonDown || Keyboard.GetState().IsAnyKeyDown;
```
Comment (emmauss) [inline Ryujinx.Input/Assigner/GamepadButtonAssigner.cs:60]: This should probably be remove if not being used.

File: Ryujinx.Input/Assigner/GamepadButtonAssigner.cs [hunk 22]
```diff
@@ -0,0 +1,230 @@
...
+                        value = y;
+                    }
+                    else
+                    {
+                        continue;
+                    }
+
+                    _detector.AddInput((GamepadButtonInputId)inputId, value);
+                }
+
```
Comment (emmauss) [inline Ryujinx.Input/Assigner/GamepadButtonAssigner.cs:111]: Rogue white space

**Review by emmauss — CHANGES_REQUESTED** [review]
Did a quick review. Looks good,other than a couple small issues.

**Comment by albfan** [comment]
Just tested this about  input (one pair of combined joycons, one joycon left and one joycon right) and comparing with gamepad tool there're some controllers missing (joycon left): Both GUI based on sdl2 has several false positives (I suppose two are for joycons involved on combined joycon)

bad-detection

I just build a CLI about sdl2 and game controllers, check that controllers are mapped on GameControllers db 

https://github.com/gabomdq/SDL_GameControllerDB

and this is the output from sdl2-jstest:

https://gitlab.com/sdl-jstest/sdl-jstest

```
$ ./sdl2-jstest -l
Found 7 joystick(s)

Joystick Name:     'Nintendo Switch Right Joy-Con'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    0
Number of Axes:     2
Number of Buttons: 11
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Right Joy-Con IMU'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    1
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Right Joy-Con IMU'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    2
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con IMU'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    3
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    4
Number of Axes:     2
Number of Buttons: 11
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con IMU'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    5
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Combined Joy-Cons'
Joystick GUID:     060000007e0500000820000000000000
Joystick Number:    6
Number of Axes:     4
Number of Buttons: 22
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Combined Joy-Cons (joycond)'
  Mapping: '060000007e0500000820000000000000,Nintendo Combined Joy-Cons (joycond),a:b0,b:b1,back:b9,dpdown:b15,dpleft:b16,dpright:b17,dpup:b14,guide:b11,leftshoulder:b5,leftstick:b12,lefttrigger:b7,leftx:a0,lefty:a1,rightshoulder:b6,rightstick:b13,righttrigger:b8,rightx:a2,righty:a3,start:b10,x:b3,y:b2,platform:Linux,'
```

So filtering IMU (as we know that is not a needed controller and has only axis but no buttons) (not sure if there's other way to filter IMU joysticks) and updating game db controller I think this should be solved.

Didn't check exactly what's the sdl version we are using in this PR, will dig about sdl2 and gamecontroller db

**Comment by albfan** [comment]
All joycons are recognized after put a recent game controller db on same path as Ryujinx executable:

IMG_20210412_182301 (1)

[SDL_GameControllerDB.txt](https://github.com/Ryujinx/Ryujinx/files/6298284/SDL_GameControllerDB.txt)

But mapping is not done automatically, are we planning to map controller using game controller db?

So as controllers are recognized by GUID and this is the same for IMU and controller, filter of IMU needs to be done on Ryujinx, what do you think? I can discuss on sdl2 itself too, but probably that will involve changes on API and wrapper ppy.SDL2-CS

NOTE: is it possible to rework paths for this kind of config files to `Environment.SpecialFolder.ApplicationData` that will ease progress on #https://github.com/Ryujinx/Ryujinx/issues/1077 too

NOTE2: I will work on showing pressed buttons on Input dialog to help to see if map is correct, is that ok?

File: Ryujinx.Input/HLE/NpadController.cs [hunk 23]
```diff
@@ -0,0 +1,484 @@
...
+            {
+                // Reset states
+                State = default;
+                _motionInput = null;
+            }
+        }
+
+        private static short ClampAxis(float value)
+        {
+            if (value <= -short.MaxValue)
```
Comment (gdkchan) [inline Ryujinx.Input/HLE/NpadController.cs:324]: Shouldn't this be checking if `value >= short.MaxValue` aswell?

File: Ryujinx.Input/HLE/NpadManager.cs [hunk 24]
```diff
@@ -0,0 +1,224 @@
...
+
+            _keyboardDriver = keyboardDriver;
+            _gamepadDriver = gamepadDriver;
+            _inputConfig = ConfigurationState.Instance.Hid.InputConfig.Value;
+
+            _gamepadDriver.OnGamepadConnected += HandleOnGamepadConnected;
+            _gamepadDriver.OnGamepadDisconnected += HandleOnGamepadDisconnected;
+        }
+
+        // TODO: move that in the input manager maybe?
```
Comment (gdkchan) [inline Ryujinx.Input/HLE/NpadManager.cs:48]:
```suggestion
        // TODO: Move that in the input manager maybe?
```

File: Ryujinx.Input/HLE/NpadManager.cs [hunk 25]
```diff
@@ -0,0 +1,224 @@
...
+        private void HandleOnGamepadDisconnected(string obj)
+        {
+            // Force input reload
+            ReloadConfiguration(ConfigurationState.Instance.Hid.InputConfig.Value);
+        }
+
+        // TODO: move that in the input manager maybe?
```
Comment (gdkchan) [inline Ryujinx.Input/HLE/NpadManager.cs:55]:
```suggestion
        // TODO: Move that in the input manager maybe?
```

File: Ryujinx.Input/HLE/NpadManager.cs [hunk 26]
```diff
@@ -0,0 +1,224 @@
...
+                    else
+                    {
+                        _controllers[(int)inputConfigEntry.PlayerIndex] = controller;
+                    }
+                }
+
+                _inputConfig = inputConfig;
+
+                // Enforce an update of the property that will be updated by HLE.
+                // TODO: move that in the input manager maybe?
```
Comment (gdkchan) [inline Ryujinx.Input/HLE/NpadManager.cs:117]:
```suggestion
                // TODO: Move that in the input manager maybe?
```

File: Ryujinx.Input/IGamepad.cs [hunk 27]
```diff
@@ -0,0 +1,125 @@
...
+        /// <param name="inputId">The stick id</param>
+        /// <returns>The values of the given input joystick on the gamepad</returns>
+        (float, float) GetStick(StickInputId inputId);
+
+        /// <summary>
+        /// Get the values of a given motion sensors on the gamepad.
+        /// </summary>
+        /// <param name="inputId">The motion id</param>
+        /// <returns> The values of the given motion sensors on the gamepad.</returns>
+        /// <remarks><see cref="MotionInputId.Accelerometer"/> values are in m/s^2</remarks>
```
Comment (gdkchan) [inline Ryujinx.Input/IGamepad.cs:53]: I think this information should be on `MotionInputId`. Its a bit odd to put it on the function instead.

File: Ryujinx.Input/IGamepad.cs [hunk 28]
```diff
@@ -0,0 +1,125 @@
...
+        /// Configure the threshold of the triggers on the gamepad.
+        /// </summary>
+        /// <param name="triggerThreshold">The threshold value for the triggers on the gamepad</param>
+        void SetTriggerThreshold(float triggerThreshold);
+
+        /// <summary>
+        /// Set the configuration of the gamepad.
+        /// </summary>
+        /// <remarks>This expect config to be in the format expected by the driver</remarks>
+        /// <param name="configuration"></param>
```
Comment (gdkchan) [inline Ryujinx.Input/IGamepad.cs:67]: Missing.

File: Ryujinx.Input/IGamepad.cs [hunk 29]
```diff
@@ -0,0 +1,125 @@
...
+        /// <returns>A remapped snaphost of the state of the gamepad.</returns>
+        GamepadStateSnapshot GetMappedStateSnapshot();
+
+        /// <summary>
+        /// Get a snaphost of the state of the gamepad.
+        /// </summary>
+        /// <returns>A snaphost of the state of the gamepad.</returns>
+        GamepadStateSnapshot GetStateSnapshot();
+
+
```
Comment (gdkchan) [inline Ryujinx.Input/IGamepad.cs:90]: Double empty line.

File: Ryujinx.Input/IGamepad.cs [hunk 30]
```diff
@@ -0,0 +1,125 @@
...
+        /// <summary>
+        /// Get a snaphost of the state of a gamepad.
+        /// </summary>
+        /// <param name="gamepad">The gamepad to do a snapshot of</param>
+        /// <returns>A snaphost of the state of the gamepad.</returns>
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        public static GamepadStateSnapshot GetStateSnapshot(IGamepad gamepad)
```
Comment (gdkchan) [inline Ryujinx.Input/IGamepad.cs:97]: Same comment about `public static`.

File: Ryujinx.Input/IGamepadDriver.cs [hunk 31]
```diff
@@ -0,0 +1,37 @@
...
+{
+    /// <summary>
+    /// Represent an emulated gamepad driver used to provide input in the emulator.
+    /// </summary>
+    public interface IGamepadDriver : IDisposable
+    {
+        /// <summary>
+        /// The name of the driver
+        /// </summary>
+        public string DriverName { get; }
```
Comment (gdkchan) [inline Ryujinx.Input/IGamepadDriver.cs:13]: `public` is redundant on interfaces (more below).

File: Ryujinx.Input/IKeyboard.cs [hunk 32]
```diff
@@ -0,0 +1,41 @@
...
+        /// <returns>A snaphost of the state of the keyboard.</returns>
+        KeyboardStateSnapshot GetKeyboardStateSnapshot();
+
+        /// <summary>
+        /// Get a snaphost of the state of a keyboard.
+        /// </summary>
+        /// <param name="keyboard">The keyboard to do a snapshot of</param>
+        /// <returns>A snaphost of the state of the keyboard.</returns>
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        public static KeyboardStateSnapshot GetStateSnapshot(IKeyboard keyboard)
```
Comment (gdkchan) [inline Ryujinx.Input/IKeyboard.cs:29]: `public static`.

File: Ryujinx/Input/GTK3/GTK3Keyboard.cs [hunk 33]
```diff
@@ -0,0 +1,198 @@
...
+            {
+                stickX += 1;
+            }
+
+            if (snapshot.IsPressed((Key)stickConfig.StickLeft))
+            {
+                stickX -= 1;
+            }
+
+            OpenTK.Mathematics.Vector2 stick = new OpenTK.Mathematics.Vector2(stickX, stickY);
```
Comment (gdkchan) [inline Ryujinx/Input/GTK3/GTK3Keyboard.cs:84]: Any reason for not using `System.Numerics.Vector2` here?

File: Ryujinx/Input/GTK3/GTK3Keyboard.cs [hunk 34]
```diff
@@ -0,0 +1,198 @@
...
+                result.SetStick(StickInputId.Left, ConvertRawStickValue(leftStickX), ConvertRawStickValue(leftStickY));
+                result.SetStick(StickInputId.Right, ConvertRawStickValue(rightStickX), ConvertRawStickValue(rightStickY));
+            }
+
+            return result;
+        }
+
+        public GamepadStateSnapshot GetStateSnapshot()
+        {
+            throw new NotImplementedException();
```
Comment (gdkchan) [inline Ryujinx/Input/GTK3/GTK3Keyboard.cs:129]: If this is not supposed to be implemented, ever, then it should throw `NotSupportedException`.

File: Ryujinx/Ui/GLRenderer.cs [hunk 35]
```diff
@@ -1,40 +1,38 @@
...
+using SPB.Graphics.OpenGL;
 using System;
-using System.Collections.Generic;
 using System.Diagnostics;
+using System.Linq;
 using System.Threading;
 
+using Key = Ryujinx.Input.Key;
+
+
```
Comment (gdkchan) [inline Ryujinx/Ui/GLRenderer.cs:23]: Double empty line.

**Review by gdkchan — COMMENTED** [review]
Very nice, just need to get rid of GTK now.
I will do some testing shortly.

**Comment by albfan** [comment]
will remove al lthis as it is out of scope for this

File: Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs (hunk 18 above)
Comment (Thog) [reply Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs:14]: ok

File: Ryujinx.Input/Assigner/GamepadButtonAssigner.cs (hunk 21 above)
Comment (Thog) [reply Ryujinx.Input/Assigner/GamepadButtonAssigner.cs:60]: Missed to clean up

File: Ryujinx.Common/Configuration/ConfigurationFileFormat.cs [hunk 36]
```diff
@@ -224,14 +224,23 @@ public class ConfigurationFileFormat
         public KeyboardHotkeys Hotkeys { get; set; }
 
         /// <summary>
-        /// Keyboard control bindings
+        /// Legacy keyboard control bindings
         /// </summary>
-        public List<KeyboardConfig> KeyboardConfig { get; set; }
+        /// <remarks>Kept for file format compatibility (to avoid possible failure when parsing configuration on old versions)</remarks>
+        /// TODO: Remove this when those older versions aren't in use anymore.
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Common/Configuration/ConfigurationFileFormat.cs:230]: The configuration parsing isn't actually the issue but more the way we interact with it (aka using Includes expecting it to not be null currently on master)

File: Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs [hunk 37]
```diff
@@ -0,0 +1,10 @@
+﻿namespace Ryujinx.Common.Configuration.Hid.Controller
+{
+    public class JoyconConfigControllerStick<Button, Stick> where Button: unmanaged where Stick: unmanaged
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs:3]: The reason I made it that way is to allow different drivers configuration if we want to change it (aka something that doesn't map with the current system)

Tho maybe I can just simplify the whole thing for now I guess?

[the remark this answers is not in the document]
Comment (gdkchan) [reply Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs:3]: I actually planned to delete this comment but forgot. I think I found a valid reason for it after reading the rest of the code.

File: Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs [hunk 38]
```diff
@@ -0,0 +1,79 @@
...
+            MotionInputBackendType motionBackendType = GetMotionInputBackendType(ref reader);
+
+            switch (motionBackendType)
+            {
+                case MotionInputBackendType.GamepadDriver:
+                    return (MotionConfigController)JsonSerializer.Deserialize(ref reader, typeof(StandardMotionConfigController), options);
+                case MotionInputBackendType.CemuHook:
+                    return (MotionConfigController)JsonSerializer.Deserialize(ref reader, typeof(CemuHookMotionConfigController), options);
+                default:
+                    throw new JsonException($"Unknown backend type {motionBackendType}");
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs:60]: Not quite sure what error we should throw here tbh

File: Ryujinx.Common/Configuration/Hid/LeftJoyconCommonConfig.cs [hunk 39]
```diff
@@ -0,0 +1,23 @@
+﻿namespace Ryujinx.Common.Configuration.Hid
+{
+    public class LeftJoyconCommonConfig<Button, Stick>
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Common/Configuration/Hid/LeftJoyconCommonConfig.cs:3]: leftover I missed oops

File: Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs (hunk 37 above)
[the remark this answers is not in the document]
Comment (gdkchan) [reply Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs:3]: On another note, by convention generic type parameters are usually prefixed with `T`.

File: Ryujinx.Graphics.OpenGL/IOpenGLContext.cs [hunk 40]
```diff
@@ -0,0 +1,28 @@
...
+using System.Runtime.InteropServices;
+
+namespace Ryujinx.Graphics.OpenGL
+{
+    public interface IOpenGLContext : IDisposable
+    {
+        void MakeCurrent();
+
+        // TODO: Support more APIs per platform.
+        public static bool HasContext()
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Graphics.OpenGL/IOpenGLContext.cs:12]: Yeah the public isn't actually useful here but the static is still needed.
For Mac support we will need to readd something here yeah

File: Ryujinx.Input.SDL2/SDL2Driver.cs [hunk 41]
```diff
@@ -0,0 +1,172 @@
...
+            {
+                Logger.Debug?.Print(LogClass.Application, $"Removed joystick instance id {evnt.cbutton.which}");
+
+                OnJoystickDisconnected?.Invoke(evnt.cbutton.which);
+            }
+        }
+
+        private void EventWorker()
+        {
+            // Change this... maybe
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Input.SDL2/SDL2Driver.cs:122]: Mostly needed to choose the polling rate but missed to remove this comment (yet again..)

File: Ryujinx.Input.SDL2/SDL2GamepadDriver.cs [hunk 42]
```diff
@@ -0,0 +1,139 @@
...
+
+                // Simulate a full disconnect when disposing
+                foreach (string id in _gamepadsIds)
+                {
+                    OnGamepadDisconnected?.Invoke(id);
+                }
+
+                _gamepadsIds.Clear();
+
+                SDL2Driver.Instance.Dispose();
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Input.SDL2/SDL2GamepadDriver.cs:106]: I actually refcount in SDL2Driver

File: Ryujinx.Input/Assigner/GamepadButtonAssigner.cs [hunk 43]
```diff
@@ -0,0 +1,230 @@
...
+                        return true;
+                    }
+                }
+                
+                return false;
+            }
+
+            public List<GamepadButtonInputId> GetPressedButtons()
+            {
+                List<GamepadButtonInputId> pressedButtons = new List<GamepadButtonInputId>();
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Input/Assigner/GamepadButtonAssigner.cs:154]: nice one, will change 👍

File: Ryujinx.Input/Assigner/GamepadButtonAssigner.cs [hunk 44]
```diff
@@ -0,0 +1,230 @@
...
+                    inputSummary = new InputSummary();
+                    _stats.Add(button, inputSummary);
+                }
+
+                inputSummary.AddInput(value);
+            }
+
+            public override string ToString()
+            {
+                TextWriter writer = new StringWriter();
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Input/Assigner/GamepadButtonAssigner.cs:183]: Code from before that I just moved and used

File: Ryujinx.Input/HLE/NpadController.cs (hunk 23 above)
Comment (Thog) [reply Ryujinx.Input/HLE/NpadController.cs:324]: Code I moved again will fix

File: Ryujinx/Input/GTK3/GTK3Keyboard.cs (hunk 33 above)
Comment (Thog) [reply Ryujinx/Input/GTK3/GTK3Keyboard.cs:84]: only to keep the normalize logic that is below

File: Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs (hunk 37 above)
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs:3]: Yeah I know but wanted to make it way more explicit because I have multiple argument (so you directly see what it refer to)

File: Ryujinx.Input.SDL2/SDL2Gamepad.cs [hunk 45]
```diff
@@ -0,0 +1,361 @@
...
+        public void SetTriggerThreshold(float triggerThreshold)
+        {
+            _triggerThreshold = triggerThreshold;
+        }
+
+        public void Rumble(float lowFrequency, float highFrequency, uint durationMs)
+        {
+            if (Features.HasFlag(GamepadFeaturesFlag.Rumble))
+            {
+                ushort lowFrequencyRaw = (ushort)(lowFrequency * ushort.MaxValue);
```
[the remark this answers is not in the document]
Comment (Thog) [reply Ryujinx.Input.SDL2/SDL2Gamepad.cs:151]: Code I moved again will fix in another PR

**Comment by Thog** [comment]
Rebased and ready for reviews again

**Review by AcK77 — APPROVED** [review]

**Comment by gdkchan** [comment]
Tested with an Ipega bluetooth controller, which is the most unusual controller that I have here. Here's the issues I found:
- Button B and Right should are not recognized (they are recorgnized on master and by windows controller test utility).
- The button names on the UI do not match the ones on the controller (it shows Start as RightShoulder for example), not a big issue.
- Button presses are only registered after I release the button on the mapper which is a bit weird, however they work fine ingame.

**Review by gdkchan — APPROVED** [review]
lgtm, the problems with the controller are due to the SDL2 mappings, and its not like anyone will use this funky controller anyway.

**Review by emmauss — APPROVED** [review]
