### PR TITLE
Fix some GLXBadDrawable crashes on linux

### LINKED ISSUE #1810: Ryujinx fails to load embedded games on linux
### What's the issue you encountered?

Trying to load embedded games from games like `Psikyo Shooting Stars Bravo` and `Psikyo Shooting Stars Alpha` fails to load with the next error
```
(Ryujinx:13351): Gdk-ERROR **: 15:18:47.119: The program 'Ryujinx' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadDrawable'.
  (Details: serial 47229 error_code 160 request_code 151 (GLX) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Aborted (core dumped)
```
It started happening after PR #1560 got implemented, that made it possible to select a game from the lists
before that PR, it would just open the first game from the lists

### How can the issue be reproduced?

Try running any of the embedded games in titles that have them, while in an linux environment

### Log file

The error itself doesnt show up in the logs, but here is an debug log if it helps
[pew-pew-bundle-vol1.zip](https://github.com/Ryujinx/Ryujinx/files/5683224/pew-pew-bundle-vol1.zip)

### Environment?

- Ryujinx version: 1.0.6027</br>
- Game version: any</br>
- System Specs:
  - OS: *Arch Linux 5.9-tkg-upds
  - CPU: ryzen 5 3600
  - GPU: geforce 1050Ti
  - RAM: 16GB
- Applied Mods : No

### PR DESCRIPTION
**Pull request by SeraUQ**
fixes the crashes on linux when you stop emulation, and when you try to
exit the emulator while a game is running
tested on windows too, and didn't come up to any problems on my side

Fixes #1810

### CODE REVIEW

**Review by jduncanator — APPROVED** [review]

File: Ryujinx/Ui/MainWindow.cs [hunk 1]
```diff
@@ -604,6 +603,7 @@ private void CreateGameWindow()
                 _windowsMultimediaTimerResolution?.Dispose();
                 _windowsMultimediaTimerResolution = null;
 
+                _viewBox.Remove(GlRendererWidget);
```
Comment (mageven) [inline Ryujinx/Ui/MainWindow.cs:606]: Usually one would expect removing references to an object before disposing it, but curious that doing the opposite here fixes a problem.

**Comment by SeraUQ** [comment]
PR also fixes https://github.com/Ryujinx/Ryujinx/issues/1810

**Review by AcK77 — APPROVED** [review]
Works fine on windows! Lgtm!

**Comment by mageven** [comment]
Does this also close #1681 ?

**Comment by Alkaid-Benetnash** [comment]
@SeraUQ How did you manage to debug this issue?
I have the same "GLXBadDrawable" error as described in #1810 when using nvidia prime (linux laptop GPU offloading).
i.e.:
`./Ryujinx` -> "use intel GPU" -> bootable but slow.
`prime-run ./Ryujinx` -> "use nvidia GPU" -> "GLXBadDrawable" error

Another reddit user reported the same problem 7 month ago, [reddit link](https://www.reddit.com/r/Ryujinx/comments/i4x9ci/getting_an_error_with_nvidia_primerun_on_arch/)
I tried to break on the `gdk_x_error` but the call stack in lldb still failed to point me to a specific UI draw.
The last few call frames before the `gdk_x_error` are from libGLX_nvidia.so (no debug info available), thus not helpful neither.

Thanks!

**Comment by SeraUQ** [comment]
hey @Alkaid-Benetnash
In my case, I was trying to fix the crash when stopping emulation, so I knew where to specifically look when debugging and just tested a few things with jetbrains rider and its debugger until I the crash didnt happen anymore 

for now you could try running X with the nvidia gpu as the base one
on how to do that, google is your best friend
