### PR TITLE
ui: Initial better user error reporting

### LINKED ISSUE #587: Missing sysarchives cause Vmm fault when required by games
Attempting to access a NAND dump or sysarchive when they are not present causes a Vmm fault to be encountered, after the game attempts to read from an offset of a null pointer.

The exception looks something like this:

```
Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0x0000000000000038!
   at ChocolArm64.Memory.MemoryManager.HandleNullPte(Int64 position) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 688
   at Sub0000000008081760(CpuThreadState , MemoryManager , UInt64 , UInt64 )
   at ChocolArm64.Translator.ExecuteSubroutineA64(CpuThreadState state, MemoryManager memory, Int64 position) in C:\projects\ryujinx\ChocolArm64\Translator.cs:line 69
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in C:\projects\ryujinx\ChocolArm64\CpuThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

We should properly detect when sysarchives are accessed if they are installed or not, and throw an exception when they aren't.

cc: @emmauss @AcK77 @gdkchan

### PR DESCRIPTION
**Pull request by Thog**
This update the "No keys" dialog and block starting NSP/XCI/NCA without firmware.

Also propose to the user if they want to install firmware if they start an untrimmed XCI and remove KEYS.md as it was completely outdated.

PS: Also fix a bug with "&" in URL with OpenUrl on Windows.

Some screenshots:

image
image
image
image

Close #587

### CODE REVIEW

File: Ryujinx/Ui/Diagnostic/UserErrorDialog.cs [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+                case UserError.Unknown:
+                    return "An unknown error occured!";
+                default:
+                    return "An undefined error occured! This shouldn't happen, please contact a dev!";
+            }
+        }
+
+        private static bool IsConveredBySetupGuide(UserError error)
+        {
+            switch (error)
```
Comment (emmauss) [inline Ryujinx/Ui/Diagnostic/UserErrorDialog.cs:87]: Can't `UserError.FirmwareParsingFailed` also be handled by the guide

Comment (Thog) [reply Ryujinx/Ui/Diagnostic/UserErrorDialog.cs:87]: Oh right missed to add this one, tho we would need a section in the guide for that error later when it will be returned.
I plan to use it in next iteration (other place need to use this and I would like to handle emulator crashes too)

**Review by emmauss — APPROVED** [review]
didn't see that typo there before,lol. LGTM

File: Ryujinx/Ui/MainWindow.cs [hunk 2]
```diff
@@ -407,7 +408,71 @@ internal void LoadApplication(string path)
...
+                    {
+                        if (userError == UserError.NoFirmware)
+                        {
+                            MessageDialog shouldInstallFirmwareDialog = new MessageDialog(this, DialogFlags.Modal, MessageType.Info, ButtonsType.YesNo, null)
+                            {
+                                Title = "Ryujinx - Info",
+                                Text = "No Firmware Installed",
+                                SecondaryText = $"Would you like to install the firmware embedded in this game? (Firmware {firmwareVersion.VersionString})"
+                            };
+
```
Comment (AcK77) [inline Ryujinx/Ui/MainWindow.cs:427]: Remove extra empty line

**Review by AcK77 — APPROVED** [review]
Lgtm! Just 2 nits here. Nice work!

File: Ryujinx/Program.cs [hunk 3]
```diff
@@ -9,6 +9,7 @@
 using System;
 using System.IO;
 using System.Reflection;
+using Ryujinx.Ui.Diagnostic;
```
Comment (Xpl0itR) [inline Ryujinx/Program.cs:12]: nit: Sort using

**Review by Xpl0itR — APPROVED** [review]
One little nit, other than that it LGTM!
